---
- hosts: localhost
  vars:
    cico_data: "{{ lookup('file', './cico_data.json') | from_json }}"
    api_key: "{{ lookup('file', '~/duffy.key') }}"
  tasks:
    - name: 'Destroy node'
      cico:
        action: done
        api_key: "{{ api_key }}"
        ssid: cico_data.ssid
