---
- hosts: localhost
  gather_facts: no
  vars:
    jenkins_host: 'https://ci.centos.org'
    jenkins_job_name: ''
    jenkins_username: ''
    jenkins_password: ''
    jenkins_job_token: ''
    jenkins_download_artifacts: false
    jenkins_artifacts_directory: './artifacts'
  tasks:
    - name: "Query Jenkins job queue until job has started"
      uri:
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        method: GET
        return_content: yes
        timeout: 3
        user: "{{ jenkins_username }}"
        password: "{{ jenkins_password }}"
        url: "{{ jenkins_host }}/crumbIssuer/api/json"
      register: crumb

    - debug:
        msg: "{{ crumb.json.crumb }}"

    - name: "Set facts for parametrized build"
      set_fact:
        jenkins_build_url: "{{ jenkins_host }}/job/{{ jenkins_job_name }}/buildWithParameters?TOKEN={{ jenkins_job_token }}&{{ jenkins_job_parameters|default('')|urlencode }}"

    - name: "Start Jenkins job"
      uri:
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
          Jenkins-Crumb: "{{ crumb.json.crumb }}"
        method: POST
        return_content: yes
        status_code: 201
        user: "{{ jenkins_username }}"
        password: "{{ jenkins_password }}"
        url: "{{ jenkins_build_url }}"
      register: start_job_result

    - debug:
        msg: "{{ start_job_result }}"

    - name: "Query Jenkins job queue until job has started"
      uri:
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        method: GET
        return_content: yes
        timeout: 3
        user: "{{ jenkins_username }}"
        password: "{{ jenkins_password }}"
        url: "{{ start_job_result.location }}api/json"
      register: poll_result
      until: (poll_result.json is defined) and (poll_result.json.executable is defined) and (poll_result.json.executable.number | default(0) | int > 0)
      retries: 10
      delay: 4

    - debug:
        msg: "{{ poll_result }}"

    - name: "Jenkins build job URL"
      debug:
        msg: "Build job: {{ jenkins_host }}/job/{{ jenkins_job_name }}/{{ poll_result.json.executable.number }}/api/json"

    - name: Create folder for job link files
      file:
        state: directory
        path: "{{ jenkins_job_link_file | dirname }}"
      when: jenkins_job_link_file is defined

    - name: Write job link to a file
      copy:
        dest: "{{ jenkins_job_link_file }}"
        content: "{{ jenkins_host }}/job/{{ jenkins_job_name }}/{{ poll_result.json.executable.number }}/"
      when: jenkins_job_link_file is defined

    - name: "Poll job until it finished"
      uri:
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        method: GET
        return_content: yes
        timeout: 3
        user: "{{ jenkins_username }}"
        password: "{{ jenkins_password }}"
        url: "{{ jenkins_host }}/job/{{ jenkins_job_name }}/{{ poll_result.json.executable.number }}/api/json"
      register: build_job_result
      until: (build_job_result.json is defined) and (not build_job_result.json.building) and (build_job_result.json.result|length > 0)
      retries: 500
      delay: 30

    - name: "Create artifacts directory"
      file:
        path: "{{ jenkins_artifacts_directory }}"
        state: directory
      when: jenkins_download_artifacts | bool

    - name: "Fetch remote console log"
      get_url:
        url: "{{ jenkins_host }}/job/{{ jenkins_job_name }}/{{ poll_result.json.executable.number }}/consoleText"
        dest: "{{ jenkins_artifacts_directory }}/consoleText"
      when: jenkins_download_artifacts | bool

    - name: "Fetch remote artifacts"
      get_url:
        url: "{{ jenkins_host }}/job/{{ jenkins_job_name }}/{{ poll_result.json.executable.number }}/artifact/{{ item.relativePath }}"
        dest: "{{ jenkins_artifacts_directory }}/{{ item.fileName }}"
      loop: "{{ build_job_result.json.artifacts }}"
      when: jenkins_download_artifacts | bool

    - name: "Fail if the build failed"
      fail:
        msg: "Build Job Failed"
      when:
        - build_job_result.json.result != 'SUCCESS'
        - build_job_result.json.result != 'UNSTABLE'
