- job:
    name: packaging_build_deb_coreproject
    project-type: matrix
    logrotate:
      daysToKeep: 7
      numToKeep: -1
    properties:
      - throttle:
          max-per-node: 0
          max-total: 0
          enabled: false
          option: project
      - github:
          url: https://github.com/theforeman/foreman-packaging/
    scm:
      - foreman-deb-packaging
    axes:
      - axis:
          type: user-defined
          name: os
          values:
          - wheezy
          - jessie
          - precise
          - trusty
      - axis:
          type: slave
          name: label
          values:
          - debian
    execution-strategy:
      combination-filter: '(onlyos == "all" && os != "jessie") || onlyos == os'
    builders:
      - build_deb_coreproject
    publishers:
      - pbuilder_cleanup
    parameters:
      - string:
          name: repoowner
          default: theforeman
          description: 'GitHub username/org containing the repo, useful to change for scratch builds.<br/>
Any value other than "theforeman" will be pushed to http://stagingdeb.theforeman.org for testing.'
      - choice:
          name: project
          choices:
            - foreman
            - foreman-proxy
            - foreman-installer
          description: 'Which main project to build'
      - choice:
          name: onlyos
          choices:
            - all
            - wheezy
            - jessie
            - precise
            - trusty
          description: 'Restrict matrix job to just the one OS.'
      - string:
          name: repo
          default: develop
          description: 'Name of the sub-branch under foreman-packaging/deb to use (usually "develop" or a release name e.g. "1.2")'
      - string:
          name: version
          default: nightly
          description: 'Version of foreman being built. Primarily for apt component generation.  e.g. "nightly", "1.6"'
      - bool:
          name: gitrelease
          default: true
          description: 'Whether to label the build as a git build with a SHA as an extra changelog entry.  This <b>must</b> be disabled for releases (RC or final).'
      - choice:
          name: nightly_jenkins_job
          choices:
            - test_develop
            - test_proxy_develop
            - packaging_trigger_installer_develop
          description: 'When building nightly (develop), name of the Jenkins job that contains the source file(s) (tarballs, gems) to build, e.g. test_develop'
      - string:
          name: nightly_jenkins_job_id
          default: lastSuccessfulBuild
          description: 'When building nightly (develop), the build number for the Jenkins job (above) or an alias, e.g. 123, lastSuccessfulBuild'
