- publisher:
    name: gemset_cleanup
    publishers:
    - post-tasks:
        - matches: 
          - log-text: ""
            operator: AND
          escalate-status: false
          run-if-job-successful: false
          script: !include-raw scripts/gemset_cleanup.sh
